---
image: docker.io/eqsoft4/dockerx:${DOCKER_IMAGE_VERSION}
services:
  - name: docker.io/library/docker:${DOCKER_IMAGE_VERSION}-dind
    alias: docker

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

workflow:
  rules:
    # Trigger rules:
    # The default CI_PIPELINE_SOURCE trigger is schedule
    # Edit or comment in other trigger below

    # Create a pipline on schedules
    - if: $CI_PIPELINE_SOURCE == "schedule"

    # Create a pipline on every push commit
    # - if: $CI_PIPELINE_SOURCE == "push"

    # Create a pipeline on merge_requests_event
    # - if: $CI_PIPELINE_SOURCE == "merge_request_event"

    # Create a pipline on web "Run pipline"
    # - if: $CI_PIPELINE_SOURCE == "web" 

    # Example: Create pipeline on every push on every branch except main branch
    # - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
    #   when: never

stages:
  - check
  - build
  - test
  - deploy

.prepare:
  cache:
    - key: cache-$CI_PIPELINE_ID
      paths:
        - cache/
  variables:
    AUTOBUILDERX_REF: "stable"
    AUTOBUILDERX_REF_FILE: $AUTOBUILDERX_REF
  before_script:
    - |
      curl -L -s "https://gitlab.com/eqsoft-appstack/autobuilderx/-/archive/${AUTOBUILDERX_REF}/autobuilderx-${AUTOBUILDERX_REF_FILE}.tar.gz" | tar xzf - --strip-components=1 "autobuilderx-${AUTOBUILDERX_REF_FILE}/bin"
      chmod -R 755 bin
      export PATH=$PATH:$(pwd)/bin
  resource_group: buildx

check:
  stage: check
  script: "autobuilderx -s check"
  extends: .prepare

build:
  stage: build
  script: "autobuilderx -s build"
  extends: .prepare

test:
  stage: test
  script: "autobuilderx -s test"
  extends: .prepare

deploy:
  stage: deploy
  script: "autobuilderx -s deploy"
  extends: .prepare