---
variables:
  
  CI_DOCKER_REF: "28.3.3"
  CI_DOCKERX_IMAGE: "docker.io/stack4ops/dockerx"
  CI_DOCKERX_REF: "$CI_DOCKER_REF"

  CI_DIND_IMAGE: "docker.io/library/docker"
  CI_DIND_REF: "${CI_DOCKER_REF}-dind"
  
  CI_AUTOBUILDERX_URL: "https://gitlab.com/stack4ops/public/autobuilderx/-/archive"
  CI_AUTOBUILDERX_REF: "stable"

  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

image: "${CI_DOCKERX_IMAGE}:${CI_DOCKERX_REF}"
services:
  - name: "${CI_DIND_IMAGE}:${CI_DIND_REF}"
    alias: docker
workflow:
  rules:
    # Trigger rules:
    # The default CI_PIPELINE_SOURCE trigger is schedule
    # Edit or comment in other trigger below

    # Create a pipline on schedules
    - if: $CI_PIPELINE_SOURCE == "schedule"

    # Create a pipline on every push commit
    # - if: $CI_PIPELINE_SOURCE == "push"

    # Create a pipeline on merge_requests_event
    # - if: $CI_PIPELINE_SOURCE == "merge_request_event"

    # Create a pipline on web "Run pipline"
    # - if: $CI_PIPELINE_SOURCE == "web" 

    # Example: Create pipeline on every push on every branch except main branch
    # - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
    #   when: never

stages:
  - check
  - build
  - test
  - deploy

.prepare:
  cache:
    - key: cache-$CI_PIPELINE_ID
      paths:
        - cache/
  before_script:
    - |
      curl -L -s "${CI_AUTOBUILDERX_URL}/${CI_AUTOBUILDERX_REF}/autobuilderx-${CI_AUTOBUILDERX_REF}.tar.gz" | tar xzf - --strip-components=1 "autobuilderx-${CI_AUTOBUILDERX_REF}/bin"
      chmod -R 755 bin
      export PATH=$PATH:$(pwd)/bin
  resource_group: buildx

check:
  stage: check
  script: "autobuilderx -s check"
  extends: .prepare

build:
  stage: build
  script: "autobuilderx -s build"
  extends: .prepare

test:
  stage: test
  script: "autobuilderx -s test"
  extends: .prepare

deploy:
  stage: deploy
  script: "autobuilderx -s deploy"
  extends: .prepare